# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the local Python script to the container
COPY docker_test.py .

# Run the Python script
CMD ["python", "docker_test.py"]
